apiVersion: cloud-build-notifiers/v1
kind: GoogleChatNotifier
metadata:
  name: googlechat-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT, Build.Status.INTERNAL_ERROR, Build.Status.EXPIRED]
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
    - name: webhook-url
      value: projects/jcastle-dev/secrets/website-pipeline-notifier-webhook/versions/1
